[theme]
base = "light"
# Minimalist warm Pantone-inspired palette (balanced, unique)
primaryColor = "#FF8A5B"               # Warm coral/peach accent
backgroundColor = "#F7F5F2"            # Warm off-white (paper)
secondaryBackgroundColor = "#EFEAE4"    # Soft warm panel
textColor = "#1C1A18"                  # Deep warm ink
font = "sans serif"

[server]
headless = true

[client]
toolbarMode = "auto"