[theme]
base = "dark"
# Joel Maisel Palette
# Navy Blazer — #373B4B (deep navy) -> background
# Rifle Green — #444C38 (dark muted green) -> panels
# Crystal Teal — #3BB7B7 (bluish-green) -> primary accent
# Pomegranate — #B32727 (rich red) -> secondary accent/warn
primaryColor = "#3BB7B7"
backgroundColor = "#373B4B"
secondaryBackgroundColor = "#444C38"
textColor = "#EAECEF"  # neutral light for readability
font = "sans serif"

[server]
headless = true

[client]
toolbarMode = "auto"