[theme]
base = "dark"
# Minimalist Pantone-inspired dark palette
# Accent inspired by Pantone's "Peach Fuzz" family for approachable warmth
primaryColor = "#FFBE98"
# Deep cool background with slight blue hue for contrast and low eye strain
backgroundColor = "#0B0F14"
# Slightly lifted panels against the background
secondaryBackgroundColor = "#12161D"
# Soft off-white for high readability on dark
textColor = "#E6E7EB"
font = "sans serif"

[server]
headless = true

[client]
toolbarMode = "auto"